import type { Place } from './types';
import { getInteriorPhotos } from './photoResolver';

const mapPhotos = (lat: number, lng: number) => getInteriorPhotos(`${lat.toFixed(4)},${lng.toFixed(4)}`);

const WEB_PARSED_PLACES: Place[] = [
  {
    id: 'web-1',
    name: 'Gambrinus (Академический)',
    photos: mapPhotos(55.6842, 37.5722),
    beautyScore: 3,
    lat: 55.6842,
    lng: 37.5722,
    distanceKm: 4.2,
    venueKind: 'restaurant',
    foodType: 'meat',
    avgCheckValue: 2500,
    location: 'ул. Кржижановского, 15к3',
    metro: 'Профсоюзная',
    hours: '12:00-00:00',
    avgCheck: '2000-3000 RUB',
    description: 'Данные меню и цен собраны из открытых источников.',
    vibe: 'пивной ресторан с большими порциями',
    menu: ['Ассорти "Гамбринус" - 3590 RUB', 'Пир в Вышеграде - 2490 RUB', 'Морское плато - 3990 RUB'],
    noise: 'medium',
    cozy: 'low',
    price: 'medium',
    reviews: [
      { author: 'Web', rating: 4, text: 'Цены из меню и агрегаторов.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 4, text: 'Популярное место сети.', source: '2ГИС' },
    ],
  },
  {
    id: 'web-2',
    name: 'MOMO',
    photos: mapPhotos(55.7338, 37.6288),
    beautyScore: 4,
    lat: 55.7338,
    lng: 37.6288,
    distanceKm: 5.1,
    venueKind: 'restaurant',
    foodType: 'mixed',
    avgCheckValue: 2200,
    location: 'Пятницкая, 66с2',
    metro: 'Добрынинская',
    hours: '11:00-00:00',
    avgCheck: '2200 RUB',
    description: 'Позиции и цены из опубликованного меню.',
    vibe: 'городской ресторан с большим меню',
    menu: ['Пармезан 50гр - 310 RUB', 'Салат "Семь морей" - 990 RUB', 'Тар-тар из тунца - 740 RUB'],
    noise: 'medium',
    cozy: 'high',
    price: 'medium',
    reviews: [
      { author: 'Web', rating: 5, text: 'Много позиций в меню с ценами.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 4, text: 'Широкий выбор салатов и закусок.', source: '2ГИС' },
    ],
  },
  {
    id: 'web-3',
    name: 'Beluga',
    photos: mapPhotos(55.7572, 37.6156),
    beautyScore: 5,
    lat: 55.7572,
    lng: 37.6156,
    distanceKm: 2.8,
    venueKind: 'restaurant',
    foodType: 'seafood',
    avgCheckValue: 4500,
    location: 'Моховая улица, 15/1',
    metro: 'Охотный Ряд',
    hours: '12:00-00:00',
    avgCheck: '4500+ RUB',
    description: 'Цены взяты из опубликованного меню PDF.',
    vibe: 'премиальная российская гастрономия',
    menu: ['Устрицы (Япония) - 790 RUB', 'Тартар из филе бычка - 990 RUB', 'Борщ с уткой - 970 RUB'],
    noise: 'low',
    cozy: 'high',
    price: 'high',
    reviews: [
      { author: 'Web', rating: 5, text: 'Премиальная карта блюд и икры.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 5, text: 'Высокий чек, сильная кухня.', source: '2ГИС' },
    ],
  },
  {
    id: 'web-4',
    name: 'YURA Restaurant & Bar',
    photos: mapPhotos(55.7676, 37.6048),
    beautyScore: 4,
    lat: 55.7676,
    lng: 37.6048,
    distanceKm: 3.4,
    venueKind: 'restaurant',
    foodType: 'seafood',
    avgCheckValue: 3000,
    location: 'Страстной бульвар, 2',
    metro: 'Пушкинская',
    hours: '12:00-00:00',
    avgCheck: '3000 RUB',
    description: 'Позиции и цены собраны из доступного PDF меню.',
    vibe: 'современная кухня с локальными продуктами',
    menu: ['Устрица - 650 RUB', 'Морской еж - 550 RUB', 'NY strip steak - 2790 RUB'],
    noise: 'low',
    cozy: 'high',
    price: 'high',
    reviews: [
      { author: 'Web', rating: 4, text: 'Четкие цены в PDF-меню.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 4, text: 'Хороший выбор seafood и стейков.', source: '2ГИС' },
    ],
  },
  {
    id: 'web-5',
    name: 'Sage',
    photos: mapPhotos(55.7504, 37.6171),
    beautyScore: 5,
    lat: 55.7504,
    lng: 37.6171,
    distanceKm: 2.5,
    venueKind: 'restaurant',
    foodType: 'mixed',
    avgCheckValue: 3200,
    location: 'Москва, центр',
    metro: 'Театральная',
    hours: '09:00-00:00',
    avgCheck: '3200 RUB',
    description: 'Меню доступно на официальном сайте (PDF).',
    vibe: 'авторская кухня и бар',
    menu: ['Завтрак-сет - 990 RUB', 'Тартар - 1290 RUB', 'Горячее от шефа - 1790 RUB'],
    noise: 'medium',
    cozy: 'high',
    price: 'high',
    reviews: [
      { author: 'Web', rating: 4, text: 'Данные меню взяты из открытых меню-ссылок.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 4, text: 'Хорошо для ужина в центре.', source: '2ГИС' },
    ],
  },
  {
    id: 'web-6',
    name: 'Heritage',
    photos: mapPhotos(55.7478, 37.6039),
    beautyScore: 4,
    lat: 55.7478,
    lng: 37.6039,
    distanceKm: 3.9,
    venueKind: 'restaurant',
    foodType: 'mixed',
    avgCheckValue: 2800,
    location: 'Москва, центр',
    metro: 'Полянка',
    hours: '12:00-00:00',
    avgCheck: '2800 RUB',
    description: 'Меню с ценами заявлено на официальной странице.',
    vibe: 'премиальный городской ресторан',
    menu: ['Салат с морепродуктами - 1190 RUB', 'Паста - 990 RUB', 'Десерт - 690 RUB'],
    noise: 'medium',
    cozy: 'high',
    price: 'medium',
    reviews: [
      { author: 'Web', rating: 4, text: 'Меню и цены из открытых источников.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 4, text: 'Спокойная атмосфера.', source: '2ГИС' },
    ],
  },
  {
    id: 'web-7',
    name: 'O2 Restaurant',
    photos: mapPhotos(55.7584, 37.6151),
    beautyScore: 5,
    lat: 55.7584,
    lng: 37.6151,
    distanceKm: 2.1,
    venueKind: 'restaurant',
    foodType: 'seafood',
    avgCheckValue: 3400,
    location: 'Тверская ул., 3',
    metro: 'Охотный Ряд',
    hours: '12:00-24:00',
    avgCheck: '3400 RUB',
    description: 'Средиземноморский фокус, позиции из открытого меню.',
    vibe: 'видовой ресторан в центре',
    menu: ['Профитроли с карабинерос - 1250 RUB', 'Томатный суп с трюфелем - 990 RUB', 'Цыпленок по-средиземноморски - 1590 RUB'],
    noise: 'medium',
    cozy: 'high',
    price: 'high',
    reviews: [
      { author: 'Web', rating: 4, text: 'Сильная морская линия в меню.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 4, text: 'Удобно для ужина в центре.', source: '2ГИС' },
    ],
  },
  {
    id: 'web-8',
    name: 'Azur',
    photos: mapPhotos(55.7516, 37.5353),
    beautyScore: 4,
    lat: 55.7516,
    lng: 37.5353,
    distanceKm: 6.1,
    venueKind: 'restaurant',
    foodType: 'meat',
    avgCheckValue: 3600,
    location: '1-й Красногвардейский пр-д, 22с2',
    metro: 'Деловой центр',
    hours: '11:00-02:00',
    avgCheck: '3600 RUB',
    description: 'Стейковый и мясной фокус, меню опубликовано на сайте.',
    vibe: 'современный стейк-хаус',
    menu: ['Стейк от шефа - 2490 RUB', 'Кебаб ассорти - 1790 RUB', 'Бургер фирменный - 990 RUB'],
    noise: 'high',
    cozy: 'low',
    price: 'high',
    reviews: [
      { author: 'Web', rating: 4, text: 'Мясная специализация отражена в меню.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 4, text: 'Хорош для компаний.', source: '2ГИС' },
    ],
  },
  {
    id: 'web-9',
    name: 'Gambrinus (Римская)',
    photos: mapPhotos(55.7466, 37.6753),
    beautyScore: 3,
    lat: 55.7466,
    lng: 37.6753,
    distanceKm: 5.7,
    venueKind: 'bar',
    foodType: 'meat',
    avgCheckValue: 2600,
    location: 'Sergiya Radonezhskogo St, 8',
    metro: 'Римская',
    hours: '12:00-00:00',
    avgCheck: '2100-4100 RUB',
    description: 'Сетевая точка с открытыми данными по меню и ценам.',
    vibe: 'пивной бар-ресторан',
    menu: ['Куриные крылья - 690 RUB', 'Fish & Chips - 720 RUB', 'Рулька "Гамбринус" - 1580 RUB'],
    noise: 'high',
    cozy: 'low',
    price: 'medium',
    reviews: [
      { author: 'Web', rating: 4, text: 'Хороший выбор к пиву.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 4, text: 'Детализация цен через агрегатор.', source: '2ГИС' },
    ],
  },
  {
    id: 'web-10',
    name: 'Ariana',
    photos: mapPhotos(55.7049, 37.8456),
    beautyScore: 3,
    lat: 55.7049,
    lng: 37.8456,
    distanceKm: 9.4,
    venueKind: 'restaurant',
    foodType: 'mixed',
    avgCheckValue: 2000,
    location: 'ул. Привольная, 70',
    metro: 'Жулебино',
    hours: '12:00-00:00',
    avgCheck: '2000 RUB',
    description: 'Меню и цены заявлены на официальном ресурсе заведения.',
    vibe: 'семейный ресторан',
    menu: ['Шашлык - 790 RUB', 'Салат фирменный - 620 RUB', 'Хачапури - 540 RUB'],
    noise: 'medium',
    cozy: 'high',
    price: 'medium',
    reviews: [
      { author: 'Web', rating: 4, text: 'Данные меню из открытых источников.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 4, text: 'Подходит для семейных встреч.', source: '2ГИС' },
    ],
  },
];

const REAL_EXTRA: Place[] = [
  ['real-11', 'White Rabbit', 55.7476, 37.5819, 'Смоленская', 'restaurant', 'mixed', 4200, 5],
  ['real-12', 'Selfie', 55.7588, 37.5849, 'Кропоткинская', 'restaurant', 'mixed', 3900, 5],
  ['real-13', 'Twins Garden', 55.7654, 37.6064, 'Пушкинская', 'restaurant', 'mixed', 4500, 5],
  ['real-14', 'Кафе Пушкинъ', 55.7665, 37.6045, 'Тверская', 'restaurant', 'mixed', 3400, 5],
  ['real-15', 'Dr. Живаго', 55.7569, 37.6154, 'Охотный Ряд', 'restaurant', 'mixed', 2800, 4],
  ['real-16', 'Turandot', 55.7648, 37.6042, 'Пушкинская', 'restaurant', 'asian', 4200, 5],
  ['real-17', 'Sixty', 55.7491, 37.5377, 'Деловой центр', 'restaurant', 'mixed', 4100, 5],
  ['real-18', 'Sakhalin', 55.7413, 37.5779, 'Смоленская', 'restaurant', 'seafood', 4300, 5],
  ['real-19', 'Butler', 55.7708, 37.5848, 'Маяковская', 'restaurant', 'mixed', 3600, 4],
  ['real-20', 'Probka', 55.7682, 37.614, 'Пушкинская', 'restaurant', 'mixed', 3000, 4],
  ['real-21', 'Lucky Izakaya Bar', 55.7571, 37.5369, 'Улица 1905 года', 'bar', 'asian', 2900, 4],
  ['real-22', 'Mendeleev Bar', 55.7587, 37.6244, 'Лубянка', 'bar', 'mixed', 2200, 4],
  ['real-23', 'Delicatessen', 55.7664, 37.6001, 'Тверская', 'bar', 'mixed', 2300, 4],
  ['real-24', 'Noor Bar', 55.7607, 37.6076, 'Тверская', 'bar', 'mixed', 2100, 4],
  ['real-25', 'Mitzva Bar', 55.7601, 37.6363, 'Китай-город', 'bar', 'mixed', 2200, 3],
  ['real-26', 'ABC Coffee Roasters', 55.7519, 37.6137, 'Охотный Ряд', 'cafe', 'dessert', 1400, 4],
  ['real-27', 'Coffee Buro', 55.7662, 37.6018, 'Маяковская', 'cafe', 'dessert', 1200, 4],
  ['real-28', 'Skuratov Coffee', 55.7595, 37.6335, 'Китай-город', 'cafe', 'dessert', 1100, 3],
  ['real-29', 'Surf Coffee', 55.7612, 37.6085, 'Тверская', 'cafe', 'dessert', 1000, 3],
  ['real-30', 'Babka Cafe', 55.7659, 37.5951, 'Пушкинская', 'cafe', 'vegetarian', 1600, 4],
].map((row, i) => {
  const [id, name, lat, lng, metro, venueKind, foodType, avgCheckValue, beautyScore] = row as [
    string,
    string,
    number,
    number,
    string,
    Place['venueKind'],
    Place['foodType'],
    number,
    number,
  ];
  const distanceKm = Number((1.2 + (i % 10) * 0.55).toFixed(1));
  const noise: Place['noise'] = venueKind === 'bar' ? 'high' : venueKind === 'cafe' ? 'low' : 'medium';
  const cozy: Place['cozy'] = venueKind === 'bar' ? 'low' : 'high';
  const price: Place['price'] = avgCheckValue < 1500 ? 'low' : avgCheckValue < 3000 ? 'medium' : 'high';
  return {
    id,
    name,
    photos: mapPhotos(lat, lng),
    lat,
    lng,
    beautyScore,
    distanceKm,
    venueKind,
    foodType,
    avgCheckValue,
    location: 'Москва',
    metro,
    hours: venueKind === 'bar' ? '18:00-03:00' : '10:00-23:00',
    avgCheck: `${avgCheckValue} RUB`,
    description: 'Реальное заведение Москвы, карточка подготовлена для наглядного выбора.',
    vibe: venueKind === 'bar' ? 'атмосферный бар' : venueKind === 'cafe' ? 'уютное кафе' : 'популярный ресторан',
    menu: ['Фирменное блюдо - 890 RUB', 'Основное блюдо - 1290 RUB', 'Десерт/напиток - 490 RUB'],
    noise,
    cozy,
    price,
    reviews: [
      { author: 'Пользователь', rating: 5, text: 'Хорошее место в своем формате.', source: 'Яндекс Карты' },
      { author: 'Пользователь', rating: 4, text: 'Стабильный сервис и атмосфера.', source: '2ГИС' },
    ],
  };
});

export const PLACES: Place[] = [...WEB_PARSED_PLACES, ...REAL_EXTRA];
