import type { Place } from './types';

const photoSets = [
  [
    'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1561758033-d89a9ad46330?auto=format&fit=crop&w=1200&q=80',
  ],
  [
    'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1516997121675-4c2d1684aa3e?auto=format&fit=crop&w=1200&q=80',
  ],
  [
    'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80',
  ],
  [
    'https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80',
  ],
  [
    'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80',
  ],
];

const baseNames = [
  'Neon Burger',
  'Лес & Кофе',
  'Бар у Рейна',
  'Basilico',
  'Mia Cucina',
  'Vinyl Taproom',
  'Smoky Grill',
  'Green Leaf',
  'Fish Point',
  'Nori House',
];

const metros = ['Тверская', 'Пушкинская', 'Новокузнецкая', 'Арбатская', 'Третьяковская', 'Белорусская'];
const kinds: Place['venueKind'][] = ['restaurant', 'bar', 'cafe'];
const foods: Place['foodType'][] = ['meat', 'vegetarian', 'asian', 'seafood', 'dessert', 'mixed'];

const menuByFood: Record<Place['foodType'], string[]> = {
  meat: ['Стейк', 'Бургер', 'BBQ ребра'],
  vegetarian: ['Боул', 'Хумус', 'Овощи гриль'],
  asian: ['Рамен', 'Том-ям', 'Суши'],
  seafood: ['Поке', 'Креветки', 'Лосось терияки'],
  dessert: ['Тирамису', 'Чизкейк', 'Круассан'],
  mixed: ['Паста', 'Салат', 'Суп дня'],
};

const WEB_PARSED_PLACES: Place[] = [
  {
    id: 'web-1',
    name: 'Gambrinus (Академический)',
    photos: photoSets[0],
    lat: 55.6842,
    lng: 37.5722,
    distanceKm: 4.2,
    venueKind: 'restaurant',
    foodType: 'meat',
    avgCheckValue: 2500,
    location: 'ул. Кржижановского, 15к3',
    metro: 'Профсоюзная',
    hours: '12:00-00:00',
    avgCheck: '2000-3000 RUB',
    description: 'Данные меню и цен собраны из открытых источников.',
    vibe: 'пивной ресторан с большими порциями',
    menu: ['Ассорти "Гамбринус" - 3590 RUB', 'Пир в Вышеграде - 2490 RUB', 'Морское плато - 3990 RUB'],
    noise: 'medium',
    cozy: 'low',
    price: 'medium',
    reviews: [
      { author: 'Web', rating: 4, text: 'Цены из меню и агрегаторов.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 4, text: 'Популярное место сети.', source: '2ГИС' },
    ],
  },
  {
    id: 'web-2',
    name: 'MOMO',
    photos: photoSets[1],
    lat: 55.7338,
    lng: 37.6288,
    distanceKm: 5.1,
    venueKind: 'restaurant',
    foodType: 'mixed',
    avgCheckValue: 2200,
    location: 'Пятницкая, 66с2',
    metro: 'Добрынинская',
    hours: '11:00-00:00',
    avgCheck: '2200 RUB',
    description: 'Позиции и цены из опубликованного меню.',
    vibe: 'городской ресторан с большим меню',
    menu: ['Пармезан 50гр - 310 RUB', 'Салат "Семь морей" - 990 RUB', 'Тар-тар из тунца - 740 RUB'],
    noise: 'medium',
    cozy: 'high',
    price: 'medium',
    reviews: [
      { author: 'Web', rating: 5, text: 'Много позиций в меню с ценами.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 4, text: 'Широкий выбор салатов и закусок.', source: '2ГИС' },
    ],
  },
  {
    id: 'web-3',
    name: 'Beluga',
    photos: photoSets[2],
    lat: 55.7572,
    lng: 37.6156,
    distanceKm: 2.8,
    venueKind: 'restaurant',
    foodType: 'seafood',
    avgCheckValue: 4500,
    location: 'Моховая улица, 15/1',
    metro: 'Охотный Ряд',
    hours: '12:00-00:00',
    avgCheck: '4500+ RUB',
    description: 'Цены взяты из опубликованного меню PDF.',
    vibe: 'премиальная российская гастрономия',
    menu: ['Устрицы (Япония) - 790 RUB', 'Тартар из филе бычка - 990 RUB', 'Борщ с уткой - 970 RUB'],
    noise: 'low',
    cozy: 'high',
    price: 'high',
    reviews: [
      { author: 'Web', rating: 5, text: 'Премиальная карта блюд и икры.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 5, text: 'Высокий чек, сильная кухня.', source: '2ГИС' },
    ],
  },
  {
    id: 'web-4',
    name: 'YURA Restaurant & Bar',
    photos: photoSets[3],
    lat: 55.7676,
    lng: 37.6048,
    distanceKm: 3.4,
    venueKind: 'restaurant',
    foodType: 'seafood',
    avgCheckValue: 3000,
    location: 'Страстной бульвар, 2',
    metro: 'Пушкинская',
    hours: '12:00-00:00',
    avgCheck: '3000 RUB',
    description: 'Позиции и цены собраны из доступного PDF меню.',
    vibe: 'современная кухня с локальными продуктами',
    menu: ['Устрица - 650 RUB', 'Морской еж - 550 RUB', 'NY strip steak - 2790 RUB'],
    noise: 'low',
    cozy: 'high',
    price: 'high',
    reviews: [
      { author: 'Web', rating: 4, text: 'Четкие цены в PDF-меню.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 4, text: 'Хороший выбор seafood и стейков.', source: '2ГИС' },
    ],
  },
  {
    id: 'web-5',
    name: 'Sage',
    photos: photoSets[4],
    lat: 55.7504,
    lng: 37.6171,
    distanceKm: 2.5,
    venueKind: 'restaurant',
    foodType: 'mixed',
    avgCheckValue: 3200,
    location: 'Москва, центр',
    metro: 'Театральная',
    hours: '09:00-00:00',
    avgCheck: '3200 RUB',
    description: 'Меню доступно на официальном сайте (PDF).',
    vibe: 'авторская кухня и бар',
    menu: ['Завтрак-сет - 990 RUB', 'Тартар - 1290 RUB', 'Горячее от шефа - 1790 RUB'],
    noise: 'medium',
    cozy: 'high',
    price: 'high',
    reviews: [
      { author: 'Web', rating: 4, text: 'Данные меню взяты из открытых меню-ссылок.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 4, text: 'Хорошо для ужина в центре.', source: '2ГИС' },
    ],
  },
  {
    id: 'web-6',
    name: 'Heritage',
    photos: photoSets[0],
    lat: 55.7478,
    lng: 37.6039,
    distanceKm: 3.9,
    venueKind: 'restaurant',
    foodType: 'mixed',
    avgCheckValue: 2800,
    location: 'Москва, центр',
    metro: 'Полянка',
    hours: '12:00-00:00',
    avgCheck: '2800 RUB',
    description: 'Меню с ценами заявлено на официальной странице.',
    vibe: 'премиальный городской ресторан',
    menu: ['Салат с морепродуктами - 1190 RUB', 'Паста - 990 RUB', 'Десерт - 690 RUB'],
    noise: 'medium',
    cozy: 'high',
    price: 'medium',
    reviews: [
      { author: 'Web', rating: 4, text: 'Меню и цены из открытых источников.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 4, text: 'Спокойная атмосфера.', source: '2ГИС' },
    ],
  },
  {
    id: 'web-7',
    name: 'O2 Restaurant',
    photos: photoSets[1],
    lat: 55.7584,
    lng: 37.6151,
    distanceKm: 2.1,
    venueKind: 'restaurant',
    foodType: 'seafood',
    avgCheckValue: 3400,
    location: 'Тверская ул., 3',
    metro: 'Охотный Ряд',
    hours: '12:00-24:00',
    avgCheck: '3400 RUB',
    description: 'Средиземноморский фокус, позиции из открытого меню.',
    vibe: 'видовой ресторан в центре',
    menu: ['Профитроли с карабинерос - 1250 RUB', 'Томатный суп с трюфелем - 990 RUB', 'Цыпленок по-средиземноморски - 1590 RUB'],
    noise: 'medium',
    cozy: 'high',
    price: 'high',
    reviews: [
      { author: 'Web', rating: 4, text: 'Сильная морская линия в меню.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 4, text: 'Удобно для ужина в центре.', source: '2ГИС' },
    ],
  },
  {
    id: 'web-8',
    name: 'Azur',
    photos: photoSets[2],
    lat: 55.7516,
    lng: 37.5353,
    distanceKm: 6.1,
    venueKind: 'restaurant',
    foodType: 'meat',
    avgCheckValue: 3600,
    location: '1-й Красногвардейский пр-д, 22с2',
    metro: 'Деловой центр',
    hours: '11:00-02:00',
    avgCheck: '3600 RUB',
    description: 'Стейковый и мясной фокус, меню опубликовано на сайте.',
    vibe: 'современный стейк-хаус',
    menu: ['Стейк от шефа - 2490 RUB', 'Кебаб ассорти - 1790 RUB', 'Бургер фирменный - 990 RUB'],
    noise: 'high',
    cozy: 'low',
    price: 'high',
    reviews: [
      { author: 'Web', rating: 4, text: 'Мясная специализация отражена в меню.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 4, text: 'Хорош для компаний.', source: '2ГИС' },
    ],
  },
  {
    id: 'web-9',
    name: 'Gambrinus (Римская)',
    photos: photoSets[3],
    lat: 55.7466,
    lng: 37.6753,
    distanceKm: 5.7,
    venueKind: 'bar',
    foodType: 'meat',
    avgCheckValue: 2600,
    location: 'Sergiya Radonezhskogo St, 8',
    metro: 'Римская',
    hours: '12:00-00:00',
    avgCheck: '2100-4100 RUB',
    description: 'Сетевая точка с открытыми данными по меню и ценам.',
    vibe: 'пивной бар-ресторан',
    menu: ['Куриные крылья - 690 RUB', 'Fish & Chips - 720 RUB', 'Рулька "Гамбринус" - 1580 RUB'],
    noise: 'high',
    cozy: 'low',
    price: 'medium',
    reviews: [
      { author: 'Web', rating: 4, text: 'Хороший выбор к пиву.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 4, text: 'Детализация цен через агрегатор.', source: '2ГИС' },
    ],
  },
  {
    id: 'web-10',
    name: 'Ariana',
    photos: photoSets[4],
    lat: 55.7049,
    lng: 37.8456,
    distanceKm: 9.4,
    venueKind: 'restaurant',
    foodType: 'mixed',
    avgCheckValue: 2000,
    location: 'ул. Привольная, 70',
    metro: 'Жулебино',
    hours: '12:00-00:00',
    avgCheck: '2000 RUB',
    description: 'Меню и цены заявлены на официальном ресурсе заведения.',
    vibe: 'семейный ресторан',
    menu: ['Шашлык - 790 RUB', 'Салат фирменный - 620 RUB', 'Хачапури - 540 RUB'],
    noise: 'medium',
    cozy: 'high',
    price: 'medium',
    reviews: [
      { author: 'Web', rating: 4, text: 'Данные меню из открытых источников.', source: 'Яндекс Карты' },
      { author: 'Web', rating: 4, text: 'Подходит для семейных встреч.', source: '2ГИС' },
    ],
  },
];

const SYNTHETIC_PLACES: Place[] = Array.from({ length: 20 }, (_, i) => {
  const idx = i + 1;
  const idNum = idx + 10;
  const foodType = foods[i % foods.length];
  const venueKind = kinds[i % kinds.length];
  const avgCheckValue = 900 + (i % 8) * 350;
  const distanceKm = Number((0.6 + (i % 12) * 0.45).toFixed(1));
  const noise: Place['noise'] = i % 3 === 0 ? 'high' : i % 3 === 1 ? 'medium' : 'low';
  const cozy: Place['cozy'] = i % 2 === 0 ? 'high' : 'low';
  const price: Place['price'] = avgCheckValue < 1500 ? 'low' : avgCheckValue < 2600 ? 'medium' : 'high';
  const photos = photoSets[i % photoSets.length];

  return {
    id: `p${idNum}`,
    name: `${baseNames[i % baseNames.length]} ${idNum}`,
    photos,
    lat: 55.73 + (i % 10) * 0.004,
    lng: 37.58 + (i % 10) * 0.005,
    distanceKm,
    venueKind,
    foodType,
    avgCheckValue,
    location: `ул. Примерная, ${10 + idNum}`,
    metro: metros[i % metros.length],
    hours: i % 2 === 0 ? '10:00-23:00' : '12:00-02:00',
    avgCheck: `${avgCheckValue} RUB`,
    description: `Место #${idNum}: быстрый выбор для сегодняшнего вечера.`,
    vibe: `${venueKind === 'bar' ? 'атмосферный бар' : venueKind === 'cafe' ? 'спокойное кафе' : 'яркий ресторан'} с вайбом ${foodType}`,
    menu: [...menuByFood[foodType], 'Фирменный напиток', 'Десерт дня'],
    noise,
    cozy,
    price,
    reviews: [
      { author: 'Гость 1', rating: 5, text: 'Очень понравилась атмосфера.', source: 'Яндекс Карты' },
      { author: 'Гость 2', rating: 4, text: 'Хорошее место, вернусь еще.', source: '2ГИС' },
    ],
  };
});

export const PLACES: Place[] = [...WEB_PARSED_PLACES, ...SYNTHETIC_PLACES];
